# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /home/ec2-user/front-2/_work/urban-bassoon2/urban-bassoon2
    - run: sudo npm ci --verbose
    - run: sudo npm run build --verbose
    - run: sudo cp -rfa /home/ec2-user/front-2/_work/urban-bassoon2/urban-bassoon2/build/. /usr/share/nginx/html/
    - run: sudo systemctl restart nginx
